controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 0.2 #0.5
  min_vel_x: 0.08 #0.01
  max_vel_theta: 0.7 #1.0 #1.5
  min_vel_theta: -0.7 #-1.0

  min_in_place_vel_theta: 1.0

  acc_lim_theta: 0.6
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.15

  sim_time: 4.0

  vx_samples: 18.0
  vtheta_samples: 20.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.02

  holonomic_robot: false
  
  meter_scoring: true
